#!/usr/bin/env python
import sys

import asker

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print('./ask [article.txt] nquestions')
    else:
        filename = sys.argv[1]
        nquestions = int(sys.argv[2])
        asker.ask_questions(filename, nquestions, debug=False)
